### ISSUE TITLE
issue in image.py in calling self.numpy()

### ISSUE THREAD

**Issue by janadh** [neurosnap/mudicom#4]
Hi, 
This is my code..
>>> import mudicom
>>> mu = mudicom.load("test.dcm")
>>> img=mu.image
>>> img.save_as_pil("test.jpg")
Error message: 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user1/venv/local/lib/python2.7/site-packages/mudicom/image.py", line 122, in save_as_pil
    pixel_array = self.numpy()
TypeError: 'numpy.ndarray' object is not callable

If I change the self.numpy() to self.numpy then all works fine. 

Does it need to be fixed or if I am doing anything wrong?  Thanks..

**Comment by neurosnap** [comment]
Hey, at some point I turned `numpy` into a property and not a function.  I'd be happy to hear your thoughts on the decision.

**Comment by janadh** [comment]
Hi. Thanks for the reply.  Yes, I can see the conversion. So does it mean the code in image.py  line number 99 and 120 should read as  
pixel_array = self.numpy
? 
rather than pixel_array = self.numpy()

**Comment by neurosnap** [comment]
You're right this is a bug, thanks for raising the issue!
